### ISSUE TITLE
Crear folder con archivo de prueba

### ISSUE THREAD

**Issue by dietrichson** [dietrichson/unsam_2022#1]
@ppagnone podes armar una carpeta, poner un archivo adentro y hacer un PR?
No se si es con branch o  fork en este caso, asi que fijate y por ahi documentalo en el mismo documento que armas.

**Comment by ppagnone** [comment]
@dietrichson Podes hacerlo de ambas formas, yo lo hice como fork, dado que como branch necesitarias darle acceso a cada estudiante para crear branches en tu repositorio. Con fork.. teniendo acceso ya es suficiente.. lo agregan a su repo y luego hacen un PR a tu repo.
